#!/usr/bin/env python3
"""
build_index.py

Regenerates the catalog under _index/ from the actual frontmatter of
every structured entry in research/ and wiki/. This is the direct
replacement for the "_index/ catalog" idea from le0nce/LLM-Wiki, adapted
to this repository's own schema (schema.yaml) instead of a generic
entities/concepts model.

It is read-only with respect to research/ and wiki/ — it only writes to
_index/catalog.yaml and _index/INDEX.md. Both are fully regenerated on
every run (never hand-edited), so they can never drift out of sync with
the actual entries the way a manually maintained catalog could.

Usage:
    python3 scripts/build_index.py

Run this after adding/changing any entry, and before asking Claude a
question like "what exists for R2/GL75" — Claude can then read
_index/catalog.yaml directly instead of walking every folder by hand.
"""

from __future__ import annotations

import datetime
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _repo_lib import ROOT, load_entries  # noqa: E402


def entry_to_catalog_dict(e) -> dict:
    return {
        "id": e.id,
        "type": e.type,
        "scope": {
            "connection": e.scope.get("connection"),
            "material": e.scope.get("material"),
            "experiment_level": e.scope.get("experiment_level"),
        },
        "certainty": e.certainty,
        "status": e.status,  # only ever set for OPEN_QUESTION (OPEN | RESOLVED)
        "authored_by": e.authored_by,
        "reviewed": e.reviewed,
        "path": e.rel_path,
    }


def sort_key(e):
    scope = e.scope or {}
    conn = scope.get("connection") or "ZZZ"
    mat = scope.get("material") or "ZZZ"
    return (conn, mat, e.type or "", e.id or "")


def build():
    entries, errors = load_entries()
    entries.sort(key=sort_key)

    catalog = {
        "generated_at": datetime.datetime.now().isoformat(timespec="seconds"),
        "generated_by": "scripts/build_index.py",
        "entry_count": len(entries),
        "entries": [entry_to_catalog_dict(e) for e in entries],
    }
    if errors:
        catalog["unparsed_files"] = [
            {"path": p.relative_to(ROOT).as_posix(), "reason": msg}
            for p, msg in errors
        ]

    out_dir = ROOT / "_index"
    out_dir.mkdir(exist_ok=True)

    catalog_path = out_dir / "catalog.yaml"
    with open(catalog_path, "w", encoding="utf-8") as f:
        f.write(
            "# AUTO-GENERATED by scripts/build_index.py — do not edit by hand.\n"
            "# Regenerate with: python3 scripts/build_index.py\n\n"
        )
        yaml.safe_dump(catalog, f, sort_keys=False, allow_unicode=True)

    write_index_md(out_dir / "INDEX.md", entries, errors)

    print(f"Wrote {catalog_path.relative_to(ROOT)} ({len(entries)} entries)")
    print(f"Wrote {(out_dir / 'INDEX.md').relative_to(ROOT)}")
    if errors:
        print(f"WARNING: {len(errors)} file(s) under research/ or wiki/ could not be parsed as entries — see catalog.yaml -> unparsed_files", file=sys.stderr)


def write_index_md(path: Path, entries, errors):
    lines = []
    lines.append("# Index (auto-generated — do not edit by hand)")
    lines.append("")
    lines.append(f"Generated by `scripts/build_index.py`. {len(entries)} entries found "
                  f"under `research/` and `wiki/`. Regenerate after every change: "
                  f"`python3 scripts/build_index.py`.")
    lines.append("")

    # Summary counts by connection x material
    lines.append("## Overview: entry count by scope")
    lines.append("")
    connections = ["COMMON", "R1", "R2", "R3"]
    materials = ["COMMON", "GL24h", "GL75"]
    lines.append("| Connection | Material | Entries |")
    lines.append("|---|---|---|")
    for conn in connections:
        for mat in materials:
            count = sum(
                1 for e in entries
                if (e.scope.get("connection") or "") == conn
                and (e.scope.get("material") or "") == mat
            )
            if count or (conn == "COMMON" and mat == "COMMON"):
                lines.append(f"| {conn} | {mat} | {count} |")
    lines.append("")

    # Group by connection, then material, then type
    lines.append("## Entries by scope")
    lines.append("")
    seen_scopes = sorted({
        (e.scope.get("connection") or "UNKNOWN", e.scope.get("material") or "UNKNOWN")
        for e in entries
    })
    for conn, mat in seen_scopes:
        scoped = [e for e in entries
                  if (e.scope.get("connection") or "UNKNOWN") == conn
                  and (e.scope.get("material") or "UNKNOWN") == mat]
        lines.append(f"### {conn} / {mat}")
        lines.append("")
        lines.append("| ID | Type | Certainty / Status | Authored by | Reviewed | File |")
        lines.append("|---|---|---|---|---|---|")
        for e in scoped:
            cert_or_status = e.certainty or e.status or ""
            lines.append(
                f"| {e.id or '(no id)'} | {e.type or '?'} | {cert_or_status} | "
                f"{e.authored_by or ''} | "
                f"{'' if e.reviewed is None else e.reviewed} | `{e.rel_path}` |"
            )
        lines.append("")

    if errors:
        lines.append("## Unparsed files (need attention)")
        lines.append("")
        lines.append("These files live under `research/` or `wiki/` but could not be "
                      "read as structured entries (missing/broken YAML frontmatter). "
                      "They are not README.md files, which are skipped intentionally.")
        lines.append("")
        for p, msg in errors:
            lines.append(f"- `{p.relative_to(ROOT).as_posix()}` — {msg}")
        lines.append("")

    path.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    build()
